import { useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  useEffect(() => {
    // Spoof different timing scenarios
    // - A. TopBar DOM node is ready first (0s delay) and then MFE app is imported
    // - B. MFE app is imported first and then TopBar DOM node is ready (1s delay)
    const mockDelay = [0, 1000][(Math.random() * 2) | 0]

    setTimeout(() => {
      console.log('🚀 @topbar node rendered inside <Home/>')
      const event = new Event('@lighthouse/topbar:mount')

      // Dispatch the event and set window state.
      window.isTopBarMountable = true // Useful for scenario A
      document.dispatchEvent(event) // Useful for scenario B
    }, mockDelay)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/one" className={styles.card} passHref>
            <a className={styles.card}>
              <h2>One &rarr;</h2>
              <p>
                Visit some random page called <b>One</b>.
              </p>
            </a>
          </Link>

          <Link href="/two" className={styles.card} passHref>
            <a className={styles.card}>
              <h2>Two &rarr;</h2>
              <p>
                Visit another random page called <b>Two</b>.
              </p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
